### ISSUE TITLE
sign() got an unexpected keyword argument 'claims'

### ISSUE THREAD

**Issue by atularvind** [boris-savic/python-furs-fiscal#16]
python furs_script.py
Traceback (most recent call last):
  File "furs_script.py", line 35, in <module>
    invoice_amount=66.71)
  File "build/bdist.linux-x86_64/egg/furs_fiscal/api.py", line 347, in get_invoice_eor
  File "build/bdist.linux-x86_64/egg/furs_fiscal/base_api.py", line 45, in _send_request
  File "build/bdist.linux-x86_64/egg/furs_fiscal/connector.py", line 124, in post
  File "build/bdist.linux-x86_64/egg/furs_fiscal/connector.py", line 111, in _jwt_sign
TypeError: sign() got an unexpected keyword argument 'claims'

**Comment by boris-savic** [comment]
Closed with the release of 0.4.0
